FAKE_ALUNOS = [
    {
        'nome': 'Maria Clara Santana',
        'email': 'mcmsant@unifei.edu.br',
        'universidade': 'UNIFEI - Universidade Federal de Itajubá',
        'curso': 'Engenharia de Computação',
        'ano_graduacao': 2026,
        'telefone': '(17) 99263-3564',
        'cidade': 'Itajubá',
        'estado': 'MG',
        'pais': 'Brazil',
        'cpf': '46874559800',
        'modalidade_estagio': 'Integral',
        'competencias': ['Excel', 'Programação Embarcada', 'assembly', 'SQL'],
        'ja_estagiou': False,
        'autoriza_dados': True
    },
    {
        'nome': 'Reimer Reis Macedo',
        'email': 'reisreimer@gmail.com',
        'universidade': 'UNIANHANGUERA - Anhanguera Educacional',
        'curso': 'Pós-graduação',
        'ano_graduacao': 2024,
        'telefone': '(11) 96169-8250',
        'cidade': 'São Bernardo do Campo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '47799347880',
        'modalidade_estagio': 'Integral',
        'competencias': ['PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/reimerreis',
        'data_nascimento': '18/11/1998',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Avançado',
        'area_interesse': 'Mercado Financeiro',
        'bancos_interesse': ['Itaú', 'Bradesco', 'Santander'],
        'forma_contratacao': 'Indicação',
        'objetivos': ['Buscar Vagas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Rafael Zanolini Pisarewski Moisés',
        'email': 'r215170@dac.unicamp.br',
        'universidade': 'UNICAMP - Universidade Estadual de Campinas',
        'curso': 'Engenharia de Produção',
        'ano_graduacao': 2025,
        'telefone': '(19) 98881-5011',
        'cidade': 'Limeira',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '47903863843',
        'modalidade_estagio': 'Integral',
        'competencias': ['Business Analytics', 'Data Science', 'Design de Produto', 'Engenharia de Dados', 'Gestão de Negócios', 'Gestão de Operações', 'Gestão de Projetos', 'Inteligência Artificial', 'Logística', 'Machine Learning', 'Supply Chain', 'Trading'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/rafael-zanolini-mois%C3%A9s-624abb209/',
        'data_nascimento': '08/03/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Avançado',
        'area_interesse': 'Engenharia; Tecnologia; Startup',
        'forma_contratacao': 'AMBEV',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Rafael Lacerda',
        'email': 'rafael-lacerda@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Civil',
        'ano_graduacao': 2025,
        'telefone': '(61) 98131-6539',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '5108060157',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Integral; Short Job; Outros',
        'competencias': ['Modelagem Financeira'],
        'ja_estagiou': True,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/rafael-lacerda-6b5576188/',
        'data_nascimento': '01/05/1999',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Avançado',
        'area_interesse': 'Consultoria; Mercado Financeiro',
        'forma_contratacao': 'McKinsey, Bain, BCG',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Igor Alves Cavalcante Honorio',
        'email': 'igor.cruzero157@gmail.com',
        'universidade': 'CUFSA - Centro Universitário Fundação Santo André',
        'curso': 'Análise e Desenvolvimento de Sistemas',
        'ano_graduacao': 2024,
        'telefone': '(11) 99537-8865',
        'cidade': 'Mauá',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '43024361820',
        'modalidade_estagio': 'Meio Período; Integral; Short Job',
        'competencias': ['Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '14/07/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Tecnologia',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Conhecer Áreas', 'Buscar Vagas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Laura de Farias Lameu',
        'email': 'lauralameu32@gmail.com',
        'universidade': 'Mackenzie',
        'curso': 'Psicologia',
        'ano_graduacao': 2028,
        'telefone': '(11) 96143-7763',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '39725807898',
        'modalidade_estagio': 'Estágio de Férias; Meio Período',
        'competencias': ['Certificações'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '28/06/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Saúde',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Darley Alves de Sampaio',
        'email': 'darleyalvessampaio@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Ambiental',
        'ano_graduacao': 2028,
        'telefone': '(12) 99703-3284',
        'cidade': 'Jacareí',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '46839642879',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '29/10/1999',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Consultoria; Mercado Financeiro; Tecnologia',
        'forma_contratacao': 'Opportunity',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Enzo Antonio dos Santos Vignone',
        'email': 'enzoantoniovignone@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Relações Internacionais',
        'ano_graduacao': 2027,
        'telefone': '(11) 98769-3936',
        'cidade': 'Cotia',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '46681079806',
        'modalidade_estagio': 'Estágio de Férias; Short Job; Meio Período',
        'competencias': ['Outras'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/enzo-vignone/',
        'data_nascimento': '11/01/2006',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Mercado Financeiro; Consultoria; Outros',
        'forma_contratacao': 'UBS',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Adriana Murakami Wu',
        'email': 'Adrimurakamiwu@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Civil',
        'ano_graduacao': 2029,
        'telefone': '(11) 98976-0267',
        'cidade': 'São Bernardo do Campo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '47826272890',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '18/07/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Consultoria; Engenharia',
        'forma_contratacao': 'Santander',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Luan Felipe Santos de Andrade',
        'email': 'd2021018735@unifei.edu.br',
        'universidade': 'UNIFEI - Universidade Federal de Itajubá',
        'curso': 'Engenharia de Controle e Automação',
        'ano_graduacao': 2025,
        'telefone': '(12) 99206-0404',
        'cidade': 'Itajubá',
        'estado': 'MG',
        'pais': 'Brasil',
        'cpf': '52857231830',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Integral; Short Job; Outros',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/luan-felipe-andrade/',
        'data_nascimento': '14/07/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Bens de Consumo; Engenharia; Indústria; Tecnologia; Outros; Startup',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking', 'Buscar Vagas', 'Outros'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Giovanna Orlandini Barros',
        'email': 'giovannaorlandini@hotmail.com',
        'universidade': 'FMU - Centro Universitário das Faculdades Metropolitanas Unidas',
        'curso': 'Comunicação Social - Publicidade e Propaganda',
        'ano_graduacao': 2025,
        'telefone': '(11) 97402-2346',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '48129341840',
        'modalidade_estagio': 'Integral; Meio Período',
        'competencias': ['Excel', 'PowerPoint', 'Outras', 'Adobe Creative Suite'],
        'ja_estagiou': True,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/giovanna-orlandini-barros?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
        'data_nascimento': '16/07/2001',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Tecnologia; Indústria; Saúde; Consultoria',
        'forma_contratacao': 'Salesforce',
        'objetivos': ['Buscar Vagas', 'Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'João de Moura Reis',
        'email': 'elizi@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Mecânica',
        'ano_graduacao': 2029,
        'telefone': '(11) 98203-5690',
        'cidade': 'Suzano',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '39012853850',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '02/04/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Consultoria',
        'forma_contratacao': 'BTG',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Cinthia Gabrielli Rodrigues Coelho',
        'email': 'cinthia.coelho@unesp.br',
        'universidade': 'FEG/Unesp - Faculdade de Engenharia - Câmpus de Guaratinguetá',
        'curso': 'Engenharia Mecânica',
        'ano_graduacao': 2029,
        'telefone': '(12) 99155-0659',
        'cidade': 'Guaratinguetá',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '54114254846',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Short Job',
        'competencias': ['Excel', 'PowerPoint', 'Outras', 'SAP e TOTVS'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/cinthia-coelho-b0b223249?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
        'data_nascimento': '10/11/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Consultoria; Mercado Financeiro; Engenharia; Indústria; Tecnologia; Startup; Bens de Consumo',
        'forma_contratacao': 'Basf',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Lucas Matheus Nunes',
        'email': 'lucas.matheus@sou.inteli.edu.br',
        'universidade': 'Inteli - Instituto de Tecnologia e Liderança',
        'curso': 'Sistemas de Informação',
        'ano_graduacao': 2027,
        'telefone': '(12) 99713-4109',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '52003332880',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['Python', 'Excel', 'PowerPoint', 'CSS', 'Problem Solving', 'Outras'],
        'ja_estagiou': True,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/lucas-nunes-matheus',
        'data_nascimento': '29/03/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Consultoria; Mercado Financeiro; Tecnologia',
        'forma_contratacao': 'Uber',
        'objetivos': ['Buscar Vagas', 'Conhecer Áreas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Lucas Cardoso Alcanti',
        'email': 'cardoso18th@gmail.com',
        'universidade': 'CUFSA - Centro Universitário Fundação Santo André',
        'curso': 'Análise e Desenvolvimento de Sistemas',
        'ano_graduacao': 2025,
        'telefone': '(11) 93417-4950',
        'cidade': 'Santo André',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '52359574825',
        'modalidade_estagio': 'Meio Período',
        'competencias': ['Excel', 'PowerPoint', 'Certificações'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '15/11/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Tecnologia; Outros',
        'forma_contratacao': 'SANTANDER, TOTVS',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Isabela da Silva Anjos',
        'email': 'isabela.anjos@aluno.ufabc.edu.br',
        'universidade': 'UFABC - Universidade Federal do ABC',
        'curso': 'Bacharelado em Ciências e Tecnologia',
        'ano_graduacao': 2028,
        'telefone': '(11) 95727-5560',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '49095929892',
        'modalidade_estagio': 'Meio Período',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Certificações', 'Adobe Photoshop, Ilustrator e Indesign'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '12/09/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Bens de Consumo; Engenharia; Indústria; Saúde; Tecnologia; Química',
        'forma_contratacao': 'Santander',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'BERNARDO FALASCHI ROMEIRO',
        'email': '2002.romeiro@gmail.com',
        'universidade': 'UFTM - Universidade Federal do Triângulo Mineiro',
        'curso': 'Engenharia Elétrica',
        'ano_graduacao': 2026,
        'telefone': '(16) 99260-9994',
        'cidade': 'Ribeirão Preto',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '47753185861',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Integral; Short Job; Outros',
        'competencias': ['Problem Solving', 'Java', 'PowerPoint', 'Outras'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '05/09/2002',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Engenharia; Indústria; Tecnologia; Startup',
        'forma_contratacao': 'Honda',
        'objetivos': ['Networking', 'Buscar Vagas', 'Outros', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Raphael',
        'email': 'raphaelcdomingo@usp.br',
        'universidade': 'EEL USP - Escola de Engenharia de Lorena',
        'curso': 'Engenharia Química',
        'ano_graduacao': 2026,
        'telefone': '(11) 99281-7158',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '39684065833',
        'modalidade_estagio': 'Meio Período; Estágio de Férias',
        'competencias': ['Excel', 'PowerPoint', 'Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '28/03/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Consultoria; Engenharia; Indústria; Mercado Financeiro; Química; Startup',
        'forma_contratacao': 'Embraer',
        'objetivos': ['Buscar Vagas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Alice Lopes Serejo Alves',
        'email': 'alsa.estudos@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Naval',
        'ano_graduacao': 2028,
        'telefone': '(11) 99485-7583',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '40002229889',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['PowerPoint', 'Python', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/alice-lopes-serejo-alves-727aaa321?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
        'data_nascimento': '19/04/2006',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Sem proficiência',
        'area_interesse': 'Consultoria; Mercado Financeiro; Engenharia; Indústria',
        'forma_contratacao': 'btg pactual, jp morgan',
        'objetivos': ['Networking', 'Conhecer Áreas', 'Buscar Vagas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'CARLOS EDUARDO DOS SANTOS OLIVEIRA',
        'email': 'd2020006159@unifei.edu.br',
        'universidade': 'UNIFEI - Universidade Federal de Itajubá',
        'curso': 'Engenharia Mecânica Aeronáutica',
        'ano_graduacao': 2026,
        'telefone': '(12) 98116-5595',
        'cidade': 'São José dos Campos',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '49110818804',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Integral; Short Job',
        'competencias': ['Excel', 'PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '11/07/2001',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Indústria; Tecnologia; Mercado Financeiro',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Nicole de Lira Lopez',
        'email': 'nicole.lira.lopez@gmail.com',
        'universidade': 'FEI - Centro Universitário FEI',
        'curso': 'Engenharia de Produção',
        'ano_graduacao': 2026,
        'telefone': '(11) 94212-2605',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '48863794863',
        'modalidade_estagio': 'Meio Período',
        'competencias': ['Excel', 'PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '26/05/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Consultoria; Engenharia; Tecnologia',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Giovanna Ferreira',
        'email': 'giovannaferreira2906@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Civil',
        'ano_graduacao': 2029,
        'telefone': '(12) 98173-3182',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '45270512882',
        'modalidade_estagio': 'Estágio de Férias; Short Job',
        'competencias': ['Problem Solving', 'Excel', 'PowerPoint', 'Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '29/06/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Consultoria; Bens de Consumo; Engenharia; Tecnologia',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Fernando D\'Angelo',
        'email': 'fernando.dangelo@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Arquitetura e Urbanismo',
        'ano_graduacao': 2026,
        'telefone': '(16) 98201-3750',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brazil',
        'cpf': '936476974',
        'modalidade_estagio': 'Estágio de Férias; Meio Período',
        'competencias': ['Python', 'Problem Solving', 'Outras'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '21/03/1987',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Tecnologia; Startup; Outros',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Guilherme Paulino Da Silva Morales',
        'email': 'guipaulino335@gmail.com',
        'universidade': 'Unianhanguera - Universidade Anhanguera',
        'curso': 'Análise e Desenvolvimento de Sistemas',
        'ano_graduacao': 2026,
        'telefone': '(11) 96483-5198',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '41494193884',
        'modalidade_estagio': 'Integral; Meio Período',
        'competencias': ['Excel'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '31/05/2006',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Educação; Tecnologia',
        'forma_contratacao': 'Cartazes',
        'objetivos': ['Networking', 'Buscar Vagas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Lucas Vianna de Mattos',
        'email': 'lucasvianna@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Elétrica',
        'ano_graduacao': 2024,
        'telefone': '(27) 99945-0414',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '15478973769',
        'modalidade_estagio': 'Meio Período; Integral',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '04/10/1999',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Startup; Tecnologia; Engenharia',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Buscar Vagas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Paula Yuka Sadashima',
        'email': 'sadashimapaula@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Química',
        'ano_graduacao': 2029,
        'telefone': '(11) 95933-7641',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '51222908816',
        'modalidade_estagio': 'Meio Período; Estágio de Férias',
        'competencias': ['Outras'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '09/09/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Sem proficiência',
        'area_interesse': 'Indústria; Tecnologia; Química; Farmácia',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Lívia Mota Nogueira',
        'email': 'd2022003209@unifei.edu.br',
        'universidade': 'UNIFEI - Universidade Federal de Itajubá',
        'curso': 'Engenharia de Bioprocessos',
        'ano_graduacao': 2026,
        'telefone': '(35) 98708-0676',
        'cidade': 'Itajubá',
        'estado': 'MG',
        'pais': 'Brasil',
        'cpf': '13109151642',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['Excel', 'PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '05/01/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Indústria; Saúde; Química; Farmácia; Tecnologia',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Enzo Rienzi',
        'email': 'lrienzienzo@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Civil',
        'ano_graduacao': 2028,
        'telefone': '(11) 99138-3148',
        'cidade': 'Guarulhos',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '50337716803',
        'modalidade_estagio': 'Estágio de Férias; Short Job',
        'competencias': ['Excel', 'PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '18/12/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Engenharia; Indústria; Consultoria',
        'forma_contratacao': 'Indicação',
        'objetivos': ['Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Diogo Ferraz Nazare',
        'email': 'diogo.nazare@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Mecânica',
        'ano_graduacao': 2025,
        'telefone': '(11) 97156-8968',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '39427785802',
        'modalidade_estagio': 'Integral',
        'competencias': ['Python', 'PowerPoint', 'Excel'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '23/07/2002',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Avançado',
        'area_interesse': 'Mercado Financeiro',
        'forma_contratacao': 'Instagram',
        'objetivos': ['Buscar Vagas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Gabriela Alencar Lourenço',
        'email': 'alencar.gabriela@usp.br',
        'universidade': 'EEL USP - Escola de Engenharia de Lorena',
        'curso': 'Engenharia da Produção',
        'ano_graduacao': 2029,
        'telefone': '(11) 98370-2879',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '45848125865',
        'modalidade_estagio': 'Meio Período; Estágio de Férias; Integral',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Java', 'CSS', 'Outras', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://linkedin.com/in/gabrielaalencarl',
        'data_nascimento': '20/04/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Educação; Engenharia; Saúde; Tecnologia; Startup',
        'forma_contratacao': 'BTG Pactual',
        'objetivos': ['Networking', 'Conhecer Áreas', 'Buscar Vagas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'ROZENILDA T ANDRADE',
        'email': 'rozenilda.andrade@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Administração',
        'ano_graduacao': 2021,
        'telefone': '(11) 96430-1563',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '41532333404',
        'modalidade_estagio': 'Outros',
        'competencias': ['Excel'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '08/08/1966',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Educação; Saúde',
        'forma_contratacao': 'usp',
        'objetivos': ['Outros'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Gabriel Gobbo Cordeiro',
        'email': 'gabrielcordeiro@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Mecatrônica',
        'ano_graduacao': 2027,
        'telefone': '(19) 99822-7574',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '42189731801',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Short Job',
        'competencias': ['Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '12/04/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Indústria; Tecnologia; Startup',
        'forma_contratacao': 'Embraer',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'João Victor Dias Gonçalves',
        'email': 'joaovdgon@usp.br',
        'universidade': 'EEL USP - Escola de Engenharia de Lorena',
        'curso': 'Engenharia de Produção',
        'ano_graduacao': 2029,
        'telefone': '(21) 99335-0848',
        'cidade': 'Lorena',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '19797810798',
        'modalidade_estagio': 'Estágio de Férias; Meio Período; Short Job',
        'competencias': ['Excel', 'PowerPoint', 'Problem Solving', 'Certificações'],
        'ja_estagiou': True,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/jo%C3%A3o-gon%C3%A7alves-451969156?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bt2Ha2fKJTXuihMyVIPvVSw%3D%3D',
        'data_nascimento': '17/08/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Bens de Consumo; Mercado Financeiro; Engenharia; Indústria; Tecnologia; Startup',
        'forma_contratacao': 'Itaú unibanco e BAT',
        'objetivos': ['Networking', 'Conhecer Áreas', 'Buscar Vagas'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Miguel Miranda',
        'email': 'migmiranda05@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia de Materiais',
        'ano_graduacao': 2028,
        'telefone': '(11) 94384-2025',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '48986332850',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['PowerPoint', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '12/10/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Engenharia; Indústria; Tecnologia',
        'forma_contratacao': 'Bayer',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Gilmar Vani Prates da Costa',
        'email': 'gilmar.vaniprates@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Civil',
        'ano_graduacao': 2025,
        'telefone': '(11) 99763-4618',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '48617742844',
        'modalidade_estagio': 'Integral; Estágio de Férias; Short Job',
        'competencias': ['Excel', 'PowerPoint'],
        'ja_estagiou': True,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/gilmar-prates-138ba91a5/',
        'data_nascimento': '09/10/2001',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Engenharia; Tecnologia',
        'forma_contratacao': 'Capim',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Glauco Lousada',
        'email': 'gllousada357@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Mecatrônica',
        'ano_graduacao': 2028,
        'telefone': '(85) 98150-8051',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '47266245800',
        'modalidade_estagio': 'Outros',
        'competencias': ['Outras'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '21/10/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Consultoria; Mercado Financeiro; Engenharia; Indústria; Tecnologia; Startup',
        'forma_contratacao': 'nubank',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Murilo de Andrade Porfirio',
        'email': 'muriloa.porfirio@gmail.com',
        'universidade': 'ITA - Instituto Tecnológico de Aeronáutica',
        'curso': 'Engenharia Aeroespacial',
        'ano_graduacao': 2028,
        'telefone': '(11) 98580-8538',
        'cidade': 'Guarulhos',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '2734947080',
        'modalidade_estagio': 'Estágio de Férias',
        'competencias': ['Python', 'Problem Solving', 'Certificações', 'Outras', 'Java', 'Excel', 'PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '14/01/2006',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Avançado',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Avançado',
        'area_interesse': 'Startup; Outros; Química; Tecnologia; Indústria; Engenharia; Mercado Financeiro; Bens de Consumo',
        'forma_contratacao': 'aa',
        'objetivos': ['Outros', 'Networking'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Pedro Henrique Gimenez Silva',
        'email': 'pedro.gimenezs23@gmail.com',
        'universidade': 'UNIBERO - Centro Universitário Anhanguera de São Paulo',
        'curso': 'Ciência da Computação',
        'ano_graduacao': 2026,
        'telefone': '(11) 96540-2938',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '5254520823',
        'modalidade_estagio': 'Integral; Estágio de Férias; Meio Período',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Java', 'CSS'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/pedro-gimenez-376ab324b/',
        'data_nascimento': '23/11/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Tecnologia',
        'forma_contratacao': 'Totvs',
        'objetivos': ['Buscar Vagas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Ingrid Fleming Gonçalves',
        'email': 'i241763@dac.unicamp.br',
        'universidade': 'UNICAMP - Universidade Estadual de Campinas',
        'curso': 'Estatística',
        'ano_graduacao': 2026,
        'telefone': '(11) 98432-0918',
        'cidade': 'Campinas',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '47686879895',
        'modalidade_estagio': 'Estágio de Férias; Meio Período',
        'competencias': ['Excel', 'PowerPoint', 'Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/ingrid-fleming-gon%C3%A7alves-b035922a1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
        'data_nascimento': '02/12/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Mercado Financeiro; Consultoria; Tecnologia; Outros',
        'forma_contratacao': 'BTG',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'João Augusto Meneses Anteghini',
        'email': 'jaugustomeneses@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia Naval',
        'ano_graduacao': 2027,
        'telefone': '(11) 94984-8082',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '51326557858',
        'modalidade_estagio': 'Estágio de Férias; Meio Período',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/joao-augusto-meneses-anteghini-3130b9255',
        'data_nascimento': '19/06/2002',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Consultoria; Engenharia',
        'forma_contratacao': 'BCG',
        'objetivos': ['Buscar Vagas', 'Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Monique Santana',
        'email': 'moniquesantana08@hotmail.com',
        'universidade': 'FAM - Faculdade das Américas',
        'curso': 'Psicologia',
        'ano_graduacao': 2029,
        'telefone': '(11) 94343-1968',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '38004687865',
        'modalidade_estagio': 'Meio Período; Integral',
        'competencias': ['Excel'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/monique-santana-30a9b81b9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
        'data_nascimento': '31/03/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Educação; Saúde; Tecnologia',
        'forma_contratacao': 'Bayer, Hospital Israelita Albert Einstein',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Vitor Fassio Andrade',
        'email': 'vitor.fassio.andrade@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Química',
        'ano_graduacao': 2025,
        'telefone': '(12) 99714-4796',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '45615253860',
        'modalidade_estagio': 'Integral; Short Job; Estágio de Férias',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/vitorfassioandrade/',
        'data_nascimento': '14/12/1995',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Avançado',
        'area_interesse': 'Bens de Consumo; Mercado Financeiro; Indústria; Saúde; Tecnologia; Química; Farmácia; Outros',
        'forma_contratacao': 'Itaú Unibanco',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Alison Sousa',
        'email': 'sousa.alison@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia de Materiais',
        'ano_graduacao': 2027,
        'telefone': '(11) 29550-342',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '49396119814',
        'modalidade_estagio': 'Estágio de Férias; Meio Período',
        'competencias': ['Python', 'Problem Solving', 'Certificações'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '07/09/2003',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Intermediário',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Engenharia; Tecnologia; Química; Startup',
        'forma_contratacao': 'BASF',
        'objetivos': ['Networking', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Christiane Mayumi Kato',
        'email': 'chrismkato@gmail.com',
        'universidade': 'FEI - Centro Universitário FEI',
        'curso': 'Engenharia de Produção',
        'ano_graduacao': 2026,
        'telefone': '(11) 97519-9636',
        'cidade': 'São Bernardo do Campo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '43732104893',
        'modalidade_estagio': 'Meio Período',
        'competencias': ['Excel', 'PowerPoint'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '10/04/2004',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Mercado Financeiro; Indústria',
        'forma_contratacao': 'Samsung',
        'objetivos': ['Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Leonardo Santos de Camargo',
        'email': 'leonardosantosdecamargo@usp.com',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia de Computação',
        'ano_graduacao': 2027,
        'telefone': '(41) 99284-4477',
        'cidade': 'Curitiba',
        'estado': 'PR',
        'pais': 'Brasil',
        'cpf': '8404371962',
        'modalidade_estagio': 'Integral',
        'competencias': ['Excel', 'PowerPoint', 'Python', 'Java', 'Certificações', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '22/07/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Fluente/Nativo',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Tecnologia; Startup; Mercado Financeiro',
        'forma_contratacao': 'Embraer',
        'objetivos': ['Conhecer Áreas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'TAYS MARIANA CARDOSO FONSECA',
        'email': 'taysmarianacardosofonseca@gmail.com',
        'universidade': 'USP Butantã',
        'curso': 'Física',
        'ano_graduacao': 2029,
        'telefone': '(11) 94281-6506',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '56065456837',
        'modalidade_estagio': 'Integral',
        'competencias': ['Excel'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '25/01/2006',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Intermediário',
        'nivel_word': 'Básico',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Outros',
        'forma_contratacao': 'Santander',
        'objetivos': ['Networking'],
        'disponibilidade_viagem': 'Sim',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Júlia Espírito Santo Vital',
        'email': 'julia.vital@aluno.ufabc.edu.br',
        'universidade': 'UFABC - Universidade Federal do ABC',
        'curso': 'Ciência da Computação',
        'ano_graduacao': 2030,
        'telefone': '(65) 98402-0101',
        'cidade': 'Santo André',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '6763075154',
        'modalidade_estagio': 'Meio Período; Estágio de Férias',
        'competencias': ['PowerPoint', 'Excel', 'Python'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/julia-vital/',
        'data_nascimento': '21/05/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Educação; Engenharia; Tecnologia',
        'forma_contratacao': 'Google',
        'objetivos': ['Conhecer Áreas', 'Buscar Vagas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Clara Coelho Mohammad',
        'email': 'clara.mohammad@sou.inteli.edu.br',
        'universidade': 'Inteli - Instituto de Tecnologia e Liderança',
        'curso': 'Engenharia de Software',
        'ano_graduacao': 2026,
        'telefone': '(71) 99707-6626',
        'cidade': 'São Paulo',
        'estado': 'SP',
        'pais': 'Brasil',
        'cpf': '86217885514',
        'modalidade_estagio': 'Meio Período',
        'competencias': ['Python', 'CSS', 'PowerPoint', 'Excel', 'Problem Solving'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'linkedin': 'https://www.linkedin.com/in/claramohammad/',
        'data_nascimento': '11/02/2005',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Sem proficiência',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Básico',
        'area_interesse': 'Startup; Tecnologia; Consultoria',
        'forma_contratacao': 'BTG',
        'objetivos': ['Conhecer Áreas', 'Networking'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    },
    {
        'nome': 'Igor Souza Lima e Silva Caixeta',
        'email': 'igor.caixeta@usp.br',
        'universidade': 'USP Butantã',
        'curso': 'Engenharia de Computação',
        'ano_graduacao': 2024,
        'telefone': '(35) 98707-8856',
        'cidade': 'Passos',
        'estado': 'MG',
        'pais': 'Brasil',
        'cpf': '15308948674',
        'modalidade_estagio': 'Integral; Outros; Estágio de Férias',
        'competencias': ['PowerPoint', 'Python', 'Java', 'CSS', 'Outras'],
        'ja_estagiou': False,
        'autoriza_dados': True,
        'data_nascimento': '27/09/2002',
        'deficiencia': 'Não possuo nenhum tipo de deficiência',
        'nivel_excel': 'Básico',
        'nivel_word': 'Avançado',
        'nivel_powerpoint': 'Intermediário',
        'area_interesse': 'Engenharia; Tecnologia',
        'forma_contratacao': 'BTG',
        'objetivos': ['Networking', 'Buscar Vagas', 'Conhecer Áreas'],
        'disponibilidade_viagem': 'Não',
        'disponibilidade_mudanca': 'Sim'
    }    
]